# Generated by Django 5.2 on 2025-09-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slips', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='slips',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
